<?php
error_reporting(E_STRICT|E_ALL);
date_default_timezone_set('Asia/Shanghai');
define('Encoding','utf-8');
define('DATA_PATH',dirname(ROOT_PATH).'/data/');
define('SESSION_PATH',DATA_PATH.'session/');
define('FONT_PATH',DATA_PATH.'font.ttf');
define('DB_HOST','localhost');
define('DB_NAME','ohmyseec_car');
define('DB_USER','ohmyseec_car');
define('DB_PWD','cd2Q?M?3HqTD2n]]{#');
define('CLS_PIC_PATH',ROOT_PATH.'/cls_images/');
define('CLS_PIC_URLPATH','/cls_images/');
define('CLS_PIC_W','1200');
define('CLS_PIC_H','1200');
define('CLS_PIC_ZTYPE','box');
?>